<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simpleseeuser"
 *
 * Auto generated by Extension Builder 2017-08-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'To see user',
    'description' => ' Display the user profile',
    'category' => 'plugin',
    'author' => 'Puente, Nicolás',
    'author_email' => 'nicolaspuente@yahoo.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
            'fluid' => '7.6.0',
            'extbase' => '7.6.0',
            'sr_feuser_register' => '5.0.0',
            'static_info_tables' => '6.4.3',
            'pue_spalten' => '1.0.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
